# Generated by Django 5.1.4 on 2024-12-16 17:40

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Emp',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('empid', models.CharField(max_length=200)),
                ('phone', models.CharField(max_length=10)),
                ('working', models.BooleanField(default=True)),
                ('department', models.CharField(max_length=200)),
            ],
        ),
    ]
