# Generated by Django 5.1.4 on 2025-01-24 10:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('emp', '0003_testimonial_picture'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='emp',
            name='department',
        ),
        migrations.RemoveField(
            model_name='emp',
            name='empid',
        ),
    ]
