# Generated by Django 5.1.4 on 2025-01-24 11:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('emp', '0004_remove_emp_department_remove_emp_empid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='emp',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
