# Generated by Django 5.1.4 on 2025-01-29 14:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('emp', '0007_remove_testimonial_picture_testimonial_rating'),
    ]

    operations = [
        migrations.AlterField(
            model_name='testimonial',
            name='rating',
            field=models.CharField(max_length=10),
        ),
    ]
