# Generated by Django 5.1.4 on 2024-12-13 17:29

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Students',
            fields=[
                ('name', models.CharField(max_length=200)),
                ('college', models.CharField(max_length=200)),
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('isactive', models.BooleanField(default=False)),
            ],
        ),
    ]
